name: "Gitflow Workflow Action"
description: "Create PR for release + Create GH release and send Slack message on merge"

inputs:
  version:
    description: The version to be released
    required: false
    default: ""
  version_increment:
    description: The version increment to be released
    required: false
    default: ""
  develop_branch:
    description: The branch used for development
    required: true
  main_branch:
    description: The branch used for production
    required: true
  slack:
    description: The slack options (channel, name mapping)
    required: false
  merge_back_from_main:
    description: Merge back to develop from main instead of release branch
    required: false
    default: "false"
  dry_run:
    description: Dry run, don't create PR or release
    required: false
    default: "false"
  release_summary:
    description: Specify the release summary to be put in the last section of the release
    required: false
    default: ""

runs:
  using: "node16"
  main: "dist/index.js"
