on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: "semver version to release"

name: Create release

jobs:
  pre_release:
    runs-on: ubuntu-latest
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3
      - name: gitflow-workflow-action create release
        uses: ./
        with:
          develop_branch: "develop"
          main_branch: "main"
          version: ${{ inputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
